export class Insurance {

    iD: number;
    patientInsuranceDetailID: number;
    insuranceCompanyID: number;
    insuranceCompanyName: string;
    groupName: string;
    effectiveDate: Date | null;
    effectiveDateAlt: Date | null;
    addOn: Date;
    expirationDate: Date;
    insuranceType: number; 
    insuranceTypeName: string;
    stInsuranceType: string;
    policyNumber: string;
    defaultFrequency: number | null;
    transUnionID: string;
    patientID: number;
    insuranceCompanyCode: string;
    specificCycle: number | null;
    payerRealID: string;
    portalUserName: string;
    portalPaswword: string;
    portalID: string;
    serviceProviderNumber: string;
    taxID: string;
    providerCode: string;
    referenceIdentification: string;
    insuranceDetail: string;
    eligibleStatus: string;
    subscriberID: string;
    ID: number;
    PatientInsuranceDetailID: number;
    InsuranceCompanyID: number;
    InsuranceCompanyName: string;
    GroupName: string;
    EffectiveDate: Date | null;
    EffectiveDateAlt: Date | null;
    AddOn: Date;
    ExpirationDate: Date;
    InsuranceType: number;
    InsuranceTypeName: string;
    StInsuranceType: string;
    PolicyNumber: string;
    DefaultFrequency: number | null;
    TransUnionID: string;
    PatientID: number;
    InsuranceCompanyCode: string;
    SpecificCycle: number | null;
    PayerRealID: string;
    ServiceProviderNumber: string;
    TaxID: string;
    ProviderCode: string;
    ReferenceIdentification: string;
    InsuranceDetail: string;
    EligibleStatus: string;
    SubscriberID: string;

}
