export class HPWeightLossItem{
    public Occupy:any;
    public Name:any;
    public DOB:any;
    public Medicine:any;
    public Allergy:any;
    public HeightFt:any;
    public HeightInch:any;
    public Weight:any;
    public SBp:any;
    public DBp:any;
    public Pulse:any;
    public PresMedication:any;
    public GainedWeight:any;
    public Childweight:any;
    public PCOS:any;
    public Obesity:any;
    public GastricBypass:any;
    public Diabetes:any;
    public HeartDisease:any;
    public GastricBand:any;
    public Hypercholesterolemia:any;
    public HTN:any;
    public ChildhoodObesity:any;
    public FamilyDiabetes:any;
    public FamilyPCOS:any;
    public OtherFlag:any;
    public OtherSurgeries:any;
    public RXApproved:any;
    public Contrain1:any;
    public Contrain2:any;
    public Contrain3:any;
    public Contrain4:any;
    public Contrain5:any;
    public Exercise1:any;
    public Exercise2:any;
    public Exercise3:any;
    public PlanedSurgery:any;
    public A1C:any;
    public ClinicNotes:any;
    public Notes:any;
    public BMI:any;
    public PersonHeartDisease:any;
    public PersonKidneyDisease:any;
    public PhysicianName:any;
    public ReviewedWithPatient:any;
    public RefillQty:any;
    public OtherMedicineDosage:any;
    
    // public Semaglutide:any;
    // public Tirzepatide:any;
    // public Troche: any;
    // public LipoVS:any;
    // public Sublingual:any;

    // public Sig30:any;
    // public Sig40:any;
    // public Sig50:any;
    // public Sig100:any;
    // public Sig120:any;
    // public Sig160:any;
    // public Sig200:any;
    // public B12Inj:any;
    // public B50Inj:any;
    // public B75Inj:any;
    // public B100Inj:any;
    // public B125Inj:any;
    // public B150Inj:any;
    // public B120TInj:any;
    // public B160TInj:any;
    // public Sig25Cy40m1:any;
    // public Sig25Cy40m2:any;
    // public Sig24m5:any;
    // public SubLin10:any;
    // public SubLin15:any;
    // public SubLin30:any;
    // public TroVS5:any;
    // public TroVS10:any;
    // public TroVS15:any;
    // public TroVS20:any;
    // public Sig100T30:any;
    // public Sig200T50:any;
    // public B250Inj:any;
    // public LipB12:any;
  }