import { ClinicPatientList } from "../clinicParms/clinic-patient-list";

export class PatientDetailUpdate {
    PatientID: number;
    FollowupCateID: number;
    FollowUpRuleId: number;
    IsRemainOnLiveCall: boolean;
    CompanyId: number;
    SurveyId: number;
    Email: string;
    ContactNo: string;
    PrefferedContact: string;
    ExistingCellPhoneNo: string;
    PatientContactID: number;
    PrimaryCellPhoneNo: string;
    MRN: string;
    FirstName: string;
    LastName: string;
    MiddleName: string;
    GPSuffixID: string;
    GPLanguageID: number;
    DateOfBirth: Date;
    SetupDate: Date;
    StrDateOfBirth: string;
    StrSetupDate: string;
    GPGenderID: number;
    Remarks: string;
    GPPatientClassID: number;
    GPRelationshipStatusID: number;
    GPPhysicianID: number;
    GPSleepLabID: number;
    GPAssignmentID: number;
    InActive: boolean;
    BranchId: number;
    AgencyID: number;
    AddressId: number;
    Address: string;
    City: string;
    StateId: number;
    StateName: string;
    CountryId: number;
    CountryName: string;
    ZipCode: string;
    AlternateAddress: string;
    AlternateCity: string;
    AlternateStateId: number;
    AlternateCountryId: number;
    IsAlternateAddress: boolean;
    AlternateZipCode: string;
    PatientContactSMSID:number;
    SMSNumber: string;
    UseAlternateAddressForShipping: boolean | null;
    EnableAutoShip: boolean;
    IsPrimaryAddress: boolean;
    
    GPPatientModeID: number;
    NextCall: Date;
    UpdateOn: Date;
    IsDeleted: boolean;
    IsPending: boolean;
    IsApproved: boolean;
    LastFollowup: number;
    UpdateBy: number;
    UpdateTerminal: string;
    InactiveOn: number;
    ApprovedBy: number;
    FollowUpSettingID: number;
    GPPatientProgramID: number;
    PhysicianNPI: string;
    ReferralSourceId: number;
    providerId: number | null;
    referrerPatientId: number;
    referrerPatient: ClinicPatientList;
}
